// Reducer Action Constants
export const IS_GETTING_JOURNEYS = "IS_GETTING_JOURNEYS";
export const SET_JOURNEYS_ERROR = "SET_JOURNEYS_ERROR";
export const CLEAR_JOURNEYS_ERROR = "CLEAR_JOURNEYS_ERROR";
export const ADD_JOURNEYS = "ADD_JOURNEYS";
export const CLEAR_JOURNEYS = "CLEAR_JOURNEYS";
export const SET_JOURNEYS_PAGINATION = "SET_JOURNEYS_PAGINATION";

// Saga Action Constants
export const GET_JOURNEYS_REQUEST = "GET_JOURNEYS_REQUEST";
