// Reducer Action Constants
export const IS_GETTING_PERCEPTIONS = "IS_GETTING_PERCEPTIONS";
export const SET_PERCEPTIONS_ERROR = "SET_PERCEPTIONS_ERROR";
export const CLEAR_PERCEPTIONS_ERROR = "CLEAR_PERCEPTIONS_ERROR";
export const ADD_PERCEPTIONS = "ADD_PERCEPTIONS";
export const CLEAR_PERCEPTIONS = "CLEAR_PERCEPTIONS";
export const SET_PERCEPTIONS_PAGINATION = "SET_PERCEPTIONS_PAGINATION";

// Saga Action Constants
export const GET_PERCEPTIONS_REQUEST = "GET_PERCEPTIONS_REQUEST";
