// Reducer Related Action Constants
export const SET_AUTH = 'SET_AUTH';
export const SET_USER = 'SET_USER';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const EDIT_POST_TITLE = 'EDIT_POST_TITLE';
export const EDIT_POST_CONTENT = 'EDIT_POST_CONTENT';
export const ADD_POST = 'ADD_POST';
export const SET_POST = 'SET_POST';
export const CLEAR_POST_LIST = 'CLEAR_POST_LIST';

// Saga Related Action Constants
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';