// Reducer Action constants
export const SET_PRESENCE_STATE = "SET_PRESENCE_STATE";
export const HANDLE_PRESENCE_DIFF = "HANDLE_PRESENCE_DIFF";
export const CLEAR_PRESENCE_STATE = "CLEAR_PRESENCE_STATE";
