// Reducer Action constants
export const IS_SENDING_COMMENT = "IS_SENDING_COMMENT";
export const SET_COMMENT_ERROR = "SET_COMMENT_ERROR";
export const CLEAR_COMMENT_ERROR = "CLEAR_COMMENT_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const CLEAR_COMMENTS_STATE = "CLEAR_COMMENTS_STATE";
export const SET_COMMENT_CONTENT = "SET_COMMENT_CONTENT";

// Saga Action constants
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
