// Reducer Action constants
export const IS_SENDING_JOURNEY = "IS_SENDING_JOURNEY";
export const SET_JOURNEY_ERROR = "SET_JOURNEY_ERROR";
export const CLEAR_JOURNEY_ERROR = "CLEAR_JOURNEY_ERROR";
export const SET_JOURNEY = "SET_JOURNEY";
export const SET_JOURNEY_TITLE = "SET_JOURNEY_TITLE";
export const SET_JOURNEY_DESCRIPTION = "SET_JOURNEY_DESCRIPTION";
export const SET_JOURNEY_START_DATE = "SET_JOURNEY_START_DATE";
export const SET_JOURNEY_END_DATE = "SET_JOURNEY_END_DATE";

// Saga Action constants
export const CREATE_JOURNEY_REQUEST = "CREATE_JOURNEY_REQUEST";
export const GET_JOURNEY_REQUEST = "GET_JOURNEY_REQUEST";
export const DELETE_JOURNEY_REQUEST = "DELETE_JOURNEY_REQUEST";
