export const GC_AUTH_TOKEN = "udia-auth-token";
export const REACT_APP_GRAPHQL_HTTP_ENDPOINT =
  process.env.REACT_APP_GRAPHQL_HTTP_ENDPOINT || "__SIMPLE_API_ENDPOINT__";
export const REACT_APP_SUBSCRIPTIONS_ENDPOINT =
  process.env.REACT_APP_SUBSCRIPTIONS_ENDPOINT ||
  "__SUBSCRIPTION_API_ENDPOINT__";
